name: Move to Project

on:
  issues:
    types:
      - opened

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Login
          uses: atlassian/gajira-login@master
          env:
            JIRA_BASE_URL: ${{ secrets.BASE_URL }}
            JIRA_USER_EMAIL: ${{ secrets.USER_EMAIL }}
            JIRA_API_TOKEN: ${{ secrets.A_ACCESS_TOKEN }}

        - name: Add issue
          uses: atlassian/gajira-create@v2.0.1
          with:
            project: FT
            issuetype: Task
            summary: "[GH]: ${{ github.event.issue.title }}"
            description: "${{ github.event.issue.body }}\n\nReported in: ${{ github.event.issue.html_url }}"
            fields: '{"labels": ["Triage", "from-GH"]}'
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Add to project
        uses: actions/github-script@v5
        env:
          ISSUE_ID: ${{ github.event.issue.node_id }}
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.graphql(`mutation($project:ID!,$issue:ID!) {
                addProjectNextItem(input: {projectId: $project, contentId: $issue}) {
                  projectNextItem {
                    id
                  }
                }
              }`, { project: "PN_kwHOAEVm1c0Z8A", issue: process.env.ISSUE_ID })
